---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-stable
  labels:
    app.kubernetes.io/name: business-stable
    app.kubernetes.io/part-of: application-layer
    app.kubernetes.io/component: backend-application
    app.kubernetes.io/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: business-stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-stable
        app.kubernetes.io/part-of: application-layer
        app.kubernetes.io/component: backend-application
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: business
          image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/business:$ECR_TAG
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: production
            - name: PORT
              value: '8080'
            - name: TYPEORM_HOST
              value: business.cka3r3gokfjc.sa-east-1.rds.amazonaws.com
            - name: TYPEORM_PORT
              value: '5432'
            - name: TYPEORM_DATABASE
              value: business
            - name: TYPEORM_USER
              valueFrom:
                secretKeyRef:
                  name: business
                  key: typeorm-user
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business
                  key: typeorm-password
            - name: AUTH0_NAMESPACE
              value: https://api.getbud.co
            - name: AUTH0_CLIENT_ID
              value: sC2t6uIvHC2wCN8creSkJ7npjZdkv4W9
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: business
                  key: auth0-client-secret
            - name: AUTH0_ISSUER
              value: https://getbud.us.auth0.com/
            - name: AUTH0_AUDIENCE
              value: https://api.getbud.co/business
            - name: GRAPHQL_SCHEMA_FILE_PATH
              value: './dist/src/app/graphql/schema.gql'
            - name: LOGGING_LEVEL
              value: error
            - name: LOGGING_SERVICE_NAME
              value: business@stable
            - name: GLOBAL_PREFIX
              value: business
            - name: CORS_ALLOWED_ORIGINS
              value: https://app.getbud.co
