version: '3.7'

volumes:
  postgres:

services:
  db-postgres:
    image: postgres
    container_name: bud-business-db-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: postgres
        target: ${POSTGRES_DATA:-/data/postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    networks:
      - bud-business

  rabbitmq:
    image: rabbitmq:management
    networks:
      - bud-rabbitmq
    ports:
      - 5672:5672
      - 8081:15672

  # business:
  #   build:
  #       context: .
  #       args:
  #         GITHUB_TOKEN: $GITHUB_TOKEN
  #         SENTRY_AUTH_TOKEN: 'b6f2dd2050764192880ec25049ebf0b538103570277b4fdb9004275dbe8630fb'
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - bud-business
  #     - bud-rabbitmq
  #   env_file:
  #     - ./.env.docker

networks:
  bud-rabbitmq:
    external: true
  bud-business:
