version: '3.7'

volumes:
  postgres:
  postgres-llms:
  postgres-mission-control:


services:
  db-postgres:
    image: postgres
    container_name: bud-business-db-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: postgres
        target: ${POSTGRES_DATA:-/data/postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    networks:
      - bud-business

  db-postgres-llms:
    image: postgres
    container_name: llms-postgres
    restart: always
    tty: true
    ports:
      - 5462:5432
    volumes:
      - type: volume
        source: postgres-llms
        target: /data/postgres-llms
    environment:
      - POSTGRES_USER=llmsdomain
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=llms

  rabbitmq:
    image: rabbitmq:management
    networks:
      - bud-rabbitmq
    ports:
      - 5672:5672
      - 8081:15672

  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sns,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack_setup:/etc/localstack/init/ready.d
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  db-postgres-mission-control:
    image: quay.io/tembo/pgmq-pg:latest
    container_name: mission-control-postgres
    restart: always
    tty: true
    ports:
      - 5472:5432
    volumes:
      - type: volume
        source: postgres-mission-control
        target: /data/postgres-mission-control
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mission-control
  # business:
  #   build:
  #       context: .
  #       args:
  #         GITHUB_TOKEN: $GITHUB_TOKEN
  #         SENTRY_AUTH_TOKEN: 'b6f2dd2050764192880ec25049ebf0b538103570277b4fdb9004275dbe8630fb'
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - bud-business
  #     - bud-rabbitmq
  #   env_file:
  #     - ./.env.docker

networks:
  bud-rabbitmq:
    external: true
  bud-business:
