version: '3.7'

volumes:
  postgres:

services:
  db-postgres:
    image: postgres
    container_name: bud-business-db-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: postgres
        target: ${POSTGRES_DATA:-/data/postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}

  broker-nats:
    image: nats
    container_name: bud-business-broker-nats
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - ${NATS_PORT:-4222}:4222
