# EXTERNAL SOURCES
# -------------------------------------------------------------------------------------------------
---
# [AUTH0] Get management API access token
POST /oauth/token
Host: getbud.us.auth0.com
Content-Type: application/json
@protocol: https

{
  "grant_type": "client_credentials",
  "client_id": "sC2t6uIvHC2wCN8creSkJ7npjZdkv4W9",
  "client_secret": "<YOUR-APPLICATION-CLIENT-SECRET>",
  "audience": "https://getbud.us.auth0.com/api/v2/"
}

---
# [AUTH0] Get test user roles
GET /api/v2/users/auth0|5fac500e2887340075f019da/roles
Host: getbud.us.auth0.com
Content-Type: application/json
Authorization: Bearer <THE-GENERATED-TOKEN>
@protocol: https
