version: '3.8'

networks:
  codespace:
    driver: bridge

volumes:
  postgres:

services:
  dev-app:
    container_name: business-dev-app
    network_mode: host
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:14
    volumes:
      - ..:/workspace:cached
    environment:
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    env_file:
      - .env
      - .env.codespace
      - .env.user
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres
    container_name: business-db-postgres
    network_mode: host
    env_file:
      - .env
      - .env.codespace
      - .env.user
    volumes:
      - type: volume
        source: postgres
        target: ${POSTGRES_DATA:-/data/postgres}
    restart: unless-stopped