export enum Resource {
  PERMISSION = 'permission',
  USER = 'user',
  USER_SETTING = 'user-setting',
  TEAM = 'team',
  FLAGS = 'flags',
  CYCLE = 'cycle',
  OBJECTIVE = 'objective',
  KEY_RESULT = 'key-result',
  KEY_RESULT_SUPPORT_TEAM = 'key-result-support-team',
  KEY_RESULT_CHECK_IN = 'key-result-check-in',
  KEY_RESULT_COMMENT = 'key-result-comment',
  KEY_RESULT_CHECK_MARK = 'key-result-check-mark',
  WORKSPACE = 'workspace',
  USER_TASK = 'user-task',
}
