export const teamMember = [
  'cycle:read:company',
  'cycle:read:team',
  'key-result-check-in:create:owns',
  'key-result-check-in:delete:owns',
  'key-result-check-in:read:company',
  'key-result-check-in:read:owns',
  'key-result-check-in:read:team',
  'key-result-check-mark:create:owns',
  'key-result-check-mark:delete:owns',
  'key-result-check-mark:read:company',
  'key-result-check-mark:read:owns',
  'key-result-check-mark:read:team',
  'key-result-check-mark:update:owns',
  'key-result-comment:create:company',
  'key-result-comment:create:owns',
  'key-result-comment:create:team',
  'key-result-comment:delete:owns',
  'key-result-comment:read:company',
  'key-result-comment:read:owns',
  'key-result-comment:read:team',
  'key-result:create:owns',
  // 'key-result-custom-list:create:owns',
  // 'key-result-custom-list:delete:owns',
  // 'key-result-custom-list:read:owns',
  // 'key-result-custom-list:update:owns',
  'key-result:delete:owns',
  'key-result:read:company',
  'key-result:read:owns',
  'key-result:read:team',
  'key-result:update:owns',
  'objective:create:owns',
  'objective:delete:owns',
  'objective:read:company',
  'objective:read:owns',
  'objective:read:team',
  'objective:update:owns',
  'permission:read:owns',
  'team:read:company',
  'team:read:owns',
  'user:read:company',
  'user:read:owns',
  'user:read:team',
  'user-setting:create:owns',
  'user-setting:delete:owns',
  'user-setting:read:company',
  'user-setting:read:owns',
  'user-setting:read:team',
  'user-setting:update:owns',
  'user:update:owns',
  'workspace:read:company',
  'user:delete:owns',
]
