version: '3.7'

volumes:
  postgres:

services:
  dev-app:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:14
    network_mode: host
    env_file: .env
    volumes:
      - ..:/workspace:cached
    
  db-postgres:
    image: postgres
    container_name: business-db-postgres
    network_mode: host
    env_file: .env
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres
        target: ${POSTGRES_DATA:-/data/postgres}
