version: '3.7'

volumes:
  postgres:

services:
  dev-app:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:14
    command: tail -f /dev/null
    network_mode: host
    volumes:
      - ..:/workspace:cached
    environment:
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    env_file: 
      - .env
      - .env.user
    
  db-postgres:
    image: postgres
    container_name: business-db-postgres
    network_mode: host
    env_file:
      - .env
      - .env.user
    volumes:
      - type: volume
        source: postgres
        target: ${POSTGRES_DATA:-/data/postgres}
    restart: unless-stopped
