version: '3.8'
services:
  dev-app:
    container_name: business-dev-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ..:/workspace:cached

  postgres:
    image: postgres
    container_name: business-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DATA: ${POSTGRES_DATA:-/data/postgres}
    volumes:
      - type: volume
        source: postgres
        target: ${POSTGRES_DATA:-/data/postgres}
    ports:
      - 5432:${POSTGRES_PORT:-5432}
    restart: unless-stopped

volumes:
  postgres: