#!/usr/bin/env bash

# DEPENDENCIES
# -------------------------------------------------------------------------------------------------
# - bash 4

# Global flags
# -------------------------------------------------------------------------------------------------
set +m

# Global variables
# -------------------------------------------------------------------------------------------------

ROOT_DIR=$(git rev-parse --show-toplevel)

# Entrypoint
# -------------------------------------------------------------------------------------------------

function main {
  validate_requirements
  setup_dependencies
  setup_base_image
}

# Validate requirements
# -------------------------------------------------------------------------------------------------

function validate_requirements {
  validate_bash_dependency
}

function validate_bash_dependency {
  major_version="$(bash --version | head -1 | cut -d ' ' -f 4 | cut -d '.' -f 1)"
  min_major_version="4"

  if [ "${major_version}" -lt "${min_major_version}" ]; then
    throw_error "Your bash major version must be ${min_major_version} or greater"
  fi
}

# Setup dependencies
# -------------------------------------------------------------------------------------------------

function setup_dependencies {
  install_pg_client
  define_node_version
}

function install_pg_client {
  log "Installing Postgres client" "Setup dependencies"

  sudo apt-get install -y postgresql-client
}

function define_node_version {
  log "Installing Node version" "Setup dependencies"

  nvm install v15.5.1
  nvm use --delete-prefix v15.5.1
}

# Setup base image
# -------------------------------------------------------------------------------------------------

function setup_base_image {
  install_application_dependencies
  build_application
  build_base_image
}

function install_application_dependencies {
  log "Installing application dependencies" "Setup base image"

  npm install
}

function build_application {
  log "Building application" "Setup base image"

  npm run build
}

function build_base_image {
  log "Building Docker base image" "Setup base image"

  docker build -t budproj/business .
}

# Helpers
# -------------------------------------------------------------------------------------------------

function log {
  message=$1
  category=${2:-Waiting}

  bold=$(tput bold)
  reset=$(tput sgr0)
  cyan=$(tput setaf 6)

  echo
  echo "${bold}${cyan}➤ ${category}:${reset} ${message}"
}

function throw_error {
  message=$1

  bold=$(tput bold)
  reset=$(tput sgr0)
  red=$(tput setaf 1)

  echo "${bold}${red}Error:${reset}"
  echo "${red}  ${message}${reset}"
  exit 1
}

# Execute
# -------------------------------------------------------------------------------------------------

main