query GET_OBJECTIVE_KEY_RESULTS($objectiveID: ID!) {
  objective(id: $objectiveID) {
    id
    keyResults {
      id
      title
      format
      goal
      initialValue
      latestKeyResultCheckIn {
        id
        value
        confidence
      }
      owner {
        id
        firstName
        fullName
        nickname
        picture
        role
        about
        linkedInProfileAddress
        teams {
          id
          name
        }
      }
      team {
        name
      }
      objective {
        cycle {
          name
          dateStart
          dateEnd
        }
      }
    }
  }
}
