query GET_TEAM_NAME($teamId: ID!) {
  team(id: $teamId) {
    id
    name
  }
}

query GET_COMPANY_OBJECTIVES {
  teams(filters: { onlyCompanies: true }) {
    id
    name
    gender
    objectives {
      id
      title
      progressIncreaseSinceLastWeek
      status {
        progress
        confidence
      }
    }
  }
}

query GET_COMPANY_TEAMS {
  teams(filters: { onlyCompanies: true }) {
    id
    teamsRanking {
      id
      name
      progressIncreaseSinceLastWeek
      status {
        progress
        confidence
      }
    }
  }
}

query GET_TEAMS {
  teams(filters: { onlyCompaniesAndDepartments: true }) {
    id
    name
    description
    isCompany
    users {
      fullName
      picture
    }
    status {
      progress
      confidence
    }
  }
}

query GET_TEAM_AND_CHILD_TEAMS_OBJECTIVES($rootTeamId: ID!) {
  team(id: $rootTeamId) {
    id
    name
    objectives {
      id
      title
      progressIncreaseSinceLastWeek
      cycle {
        dateEnd
      }
      status {
        progress
        confidence
      }
    }
    teams {
      id
      name
      objectives {
        id
        title
        progressIncreaseSinceLastWeek
        cycle {
          dateEnd
        }
        status {
          progress
          confidence
        }
      }
    }
  }
}
