query GET_USER_NAME_AND_GENDER {
  me {
    id
    firstName
    gender
  }
}

query GET_USER_PRIMARY_COMPANY {
  me {
    companies(limit: 1) {
      id
      name
      gender
      status {
        progress
        confidence
      }
      progressIncreaseSinceLastWeek
      latestKeyResultCheckIn {
        id
        createdAt
        user {
          id
          fullName
        }
      }
    }
  }
}

mutation UPDATE_USER_INFORMATION($userID: ID!, $userData: UserDataInput!) {
  updateUser(userID: $userID, userData: $userData) {
    id
    firstName
    lastName
    fullName
    nickname
    role
    gender
    about
  }
}

mutation UPDATE_USER_SOCIAL_MEDIA($userID: ID!, $userData: UserDataInput!) {
  updateUser(userID: $userID, userData: $userData) {
    id
    linkedInProfileAddress
  }
}

query GET_USER_DATA($id: ID!) {
  user(id: $id) {
    id
    firstName
    lastName
    fullName
    role
    nickname
    gender
    about
    picture
    linkedInProfileAddress
    teams {
      id
      name
    }
  }
}

query GET_USER_NAMED_AVATAR_DATA {
  me {
    id
    firstName
    fullName
    picture
    companies(limit: 1) {
      id
      name
    }
  }
}
