name: Check Tests in pull requests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    strategy:
      matrix:
        include:
        - name: Linter
          command: npm run lint
        - name: Build
          command: npm run build
        - name: Unit Tests
          command: npm test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: 
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}
